### ISSUE TITLE
application is stuck on the login page. unable to login to the application

### ISSUE THREAD

**Issue by everythingness** [git-noter/gitnoter#60]
**Describe the bug**
After successfully logging in to GitHub, nothing happens. I am just returned to the introduction page.

the URL is https://gitnoter.com/login?success=true but the page is the same as https://gitnoter.com/login

**Expected behavior**
gitnoter asks which respository i want to use

**Please provide browser information:**
 - Browsers firefox, safari
latest versions

**Comment by vivekweb2013** [comment]
@everythingness could you please try again. Since the backend server was down for maintenance, now it's up.

**Comment by everythingness** [comment]
yes still the same problem persists. also 12 hours ago.

**Comment by vivekweb2013** [comment]
@everythingness Are you using incognito mode in chrome? If yes please do not use the incognito mode. Also make sure that the browser is not blocking third party cookies since they are used for authentication

<img width="282" alt="image" src="https://user-images.githubusercontent.com/7036736/172039429-f48b80c0-0b2f-4c9c-87bb-6d541147e924.png">
In the chrome setting make sure above is unchecked

Let me know if you still getting the issue.

**Comment by vivekweb2013** [comment]
If you are using Safari please uncheck `Prevent cross-site tracking` under `Safari > Preferences > Privacy`
<img width="815" alt="image" src="https://user-images.githubusercontent.com/7036736/172040765-64cd0186-8c90-4496-b024-1371f1b64efc.png">

I'm working on implementing a proper fix for this but for now just uncheck the `Prevent cross-site tracking` in safari

**Comment by everythingness** [comment]
ah thanks for the workaround! it works now :)

**Comment by vivekweb2013** [comment]
@everythingness thanks for confirming :)

**Comment by vivekweb2013** [comment]
Hi @everythingness This issue is now fixed with the use of api subdomain. So now there is no need for changing the browser setting. Please revert the browser preferences to default and let me know if you still encounter this issue.
